spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      org.hibernate.SQL: DEBUG # 실행된 SQL 출력
      org.hibernate.type.descriptor.sql: TRACE # SQL 파라미터 출력
  application:
    name: week-01
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true

springdoc:
  swagger-ui:
    enabled: true
